import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProductDetailLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<>

    <div style={{color:"whitesmoke", backgroundColor:"CaptionText"}}>
    <div>
    <ul>
    <div>Blog</div>
    <div>Search</div>
    <div>Home</div>

  </ul>
</div>

    </div>
    <h2> ProductReview</h2>


         <div>{children}</div>

      <div style={{backgroundColor:"Highlight", textAlign:"center"}}>
            <div>
              <p>@Tech: Simple Technology Learning</p>
            </div>

        </div>
    </>
  );
}
