
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Simple Technology Learning",
    description: "Generated by TechNo",
  };

export default function About() {
  return (
    <div>About US!!!</div>
  )
}
