import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

<body>

    <header style={{color:"whitesmoke", backgroundColor:"CaptionText"}}>
    <div>
    <ul>
    <div> <Link href='/'>@Tech-Know</Link></div>
    <div> <Link href='/about'>About</Link></div>
    <div> <Link href='/contact'>Contact</Link></div>

  </ul>
</div>

    </header>


         <main className={inter.className}>{children}</main>

      <footer style={{backgroundColor:"Highlight", textAlign:"center"}}>
            <div>
              <p>@Tech: {new Date().getFullYear()}</p>
            </div>

        </footer>
    </body>
    </html>
  );
}
